apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.statestore.loyalty
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisDB
    value: "2"
scopes:
- loyalty-service