spring:
  application:
    name: accounting-service
  config:
    import: optional:classpath:.env[.properties]
  banner:
    location: static/banner.txt
server:
  port: '8707'
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    enabled: true