spring:
  application:
    name: accounting-service
  config:
    import: optional:classpath:.env[.properties]
  banner:
    location: static/banner.txt
cosmos:
  queryMetricsEnabled: 'true'
  key: ${AZURECOSMOSDBKEY}
  secondaryKey: ${AZURECOSMOSDBSECONDARYKEY}
  databaseName: ${AZURECOSMOSDBDATABASENAME}
  uri: ${AZURECOSMOSDBURI}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: false
server:
  port: '8707'
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    enabled: true