spring:
  application:
      name: order-service
  config:
    import: optional:classpath:.env[.properties]
  banner:
    location: static/banner.txt
springdoc:
  swagger-ui:
    enabled: 'true'
    path: /swagger
  api-docs:
    path: /api-docs
server:
  port: '8702'
