spring:
  application:
    name: makeline-service
  main:
    allow-bean-definition-overriding: true
  banner:
    location: static/banner.txt
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8704
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    enabled: true
---
spring:
  profiles: dev
  application:
    name: makeline-service