on:
  workflow_dispatch:
  push:
    branches:
      - main

# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read
jobs:
  build-all-services:
    uses: ./.github/actions/build-all-services.yaml@actions-setup
    secrets: inherit
  provision:
    uses: ./.github/workflows/provision-dependencies.yml@actions-setup
    needs: build-all-services
    secrets: inherit
  deploy-all-services:
    uses: ./.github/actions/build-all-services.yaml@actions-setup
    needs: provision
    secrets: inherit