on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package -DskipTests --file pom.xml
        working-directory: ./src/${{ inputs.service-name }}
      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ inputs.service-name }}
          path: target
          working-directory: ./src/${{ inputs.service-name }}